/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiStopSessionRouteImport } from './routes/api/stop-session'
import { Route as ApiLiveFeedbackRouteImport } from './routes/api/live-feedback'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStopSessionRoute = ApiStopSessionRouteImport.update({
  id: '/api/stop-session',
  path: '/api/stop-session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLiveFeedbackRoute = ApiLiveFeedbackRouteImport.update({
  id: '/api/live-feedback',
  path: '/api/live-feedback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/live-feedback': typeof ApiLiveFeedbackRoute
  '/api/stop-session': typeof ApiStopSessionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/live-feedback': typeof ApiLiveFeedbackRoute
  '/api/stop-session': typeof ApiStopSessionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/live-feedback': typeof ApiLiveFeedbackRoute
  '/api/stop-session': typeof ApiStopSessionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/live-feedback' | '/api/stop-session'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/live-feedback' | '/api/stop-session'
  id: '__root__' | '/' | '/api/live-feedback' | '/api/stop-session'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiLiveFeedbackRoute: typeof ApiLiveFeedbackRoute
  ApiStopSessionRoute: typeof ApiStopSessionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stop-session': {
      id: '/api/stop-session'
      path: '/api/stop-session'
      fullPath: '/api/stop-session'
      preLoaderRoute: typeof ApiStopSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/live-feedback': {
      id: '/api/live-feedback'
      path: '/api/live-feedback'
      fullPath: '/api/live-feedback'
      preLoaderRoute: typeof ApiLiveFeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiLiveFeedbackRoute: ApiLiveFeedbackRoute,
  ApiStopSessionRoute: ApiStopSessionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
